default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whos_hiring_development
  host: localhost
  user: ssh
  password: ssh

test:
  <<: *default
  database: whos_hiring_test
  host: localhost
  user: ssh
  password: ssh

  
production:
  <<: *default
  database: whos_hiring_production
  username: whos_hiring
  password: <%= ENV['WHOS_HIRING_DATABASE_PASSWORD'] %>