default: &default
  adapter: 'postgresql'
  database: 'db/development.sqlite'

development:
  <<: *default
    host: localhost
    user: ssh
    password: ssh

test:
  <<: *default
  database: 'db/test.sqlite'  
  host: localhost
  user: ssh
  password: ssh